// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about_me_index from "./routes/about_me/index.tsx";
import * as $basemap_index from "./routes/basemap/index.ts";
import * as $index from "./routes/index.tsx";
import * as $start_index from "./routes/start/index.tsx";
import * as $Intro from "./islands/Intro.tsx";
import * as $MapCanvas from "./islands/MapCanvas.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about_me/index.tsx": $about_me_index,
    "./routes/basemap/index.ts": $basemap_index,
    "./routes/index.tsx": $index,
    "./routes/start/index.tsx": $start_index,
  },
  islands: {
    "./islands/Intro.tsx": $Intro,
    "./islands/MapCanvas.tsx": $MapCanvas,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
